### ISSUE TITLE
warnings : may be used uninitialized in this function

### ISSUE THREAD

**Issue by golgote** [pllua/pllua-deprecated#10]
Got these warnings while compiling last merge:

plluaspi.c: In function ‘luaP_execute’:
plluaspi.c:961: attention : ‘result’ may be used uninitialized in this function
plluaspi.c: In function ‘luaP_executeplan’:
plluaspi.c:796: attention : ‘result’ may be used uninitialized in this function
plluaspi.c: In function ‘luaP_getcursorplan’:
plluaspi.c:853: attention : ‘cursor’ may be used uninitialized in this function
plluaspi.c: In function ‘luaP_rowsplan’:
plluaspi.c:878: attention : ‘cursor’ may be used uninitialized in this function

Removing macro PLLUA_PG_CATCH_RETHROW is an easy way to fix them.

Got this one as well:
pllua_pgfunc.c: In function ‘get_pgfunc’:
pllua_pgfunc.c:214: attention : ‘reg_name’ may be used uninitialized in this function

**Comment by eugwne** [comment]
PLLUA_PG_CATCH_RETHROW should protect from crashes after using code like server.execute("abracadabra")
