### ISSUE TITLE
Building against custom LuaJit in non standard location

### ISSUE THREAD

**Issue by studdugie** [pllua/pllua-deprecated#17]
Hello,

Sorry to bother you w/ my ignorance but I'm attempting to build pllua against a patched version of LuaJit-2.1.0-alpha and compilation is failing. The LuaJit that I'm trying to compile against is the same LuaJit that runs an application server platform called OpenResty so I'm confident in it's viability to run Lua even though it's -alpha.

I'm building this on/for x86_64 GNU/Linux - Ubuntu 15.10 and I've made the following changes to the Makefile:
`LUAINC = -I/opt/openresty/default/luajit/include/luajit-2.1`
`LUALIB = -L/opt/openresty/default/luajit/lib -lluajit-5.1`

But when I run make a file not found error is raised:
`plluacommon.h:29:17: fatal error: lua.h: No such file or directory`

If you could provide any guidance on what I'm doing wrong I would appreciate it.

Thank you for your consideration,

Dane

**Comment by golgote** [comment]
`LUAINC` is not used anymore in recent Makefile, you have to use `LUA_INCDIR`. This was changed for Travis integration support apparently. So your Makefile becomes:

```
LUA_INCDIR = /opt/openresty/default/luajit/include/luajit-2.1
LUALIB = -L/opt/openresty/default/luajit/lib -lluajit-5.1
```

Notice that `-I` was also removed.

**Comment by studdugie** [comment]
Great news, progress is being made. The changes made to the Makefile solved the compilation issue but now a new issue has reared its head.

When I try to install the extension in a database via `CREATE EXTENSION pllua` I get the following error:
`ERROR:  XX000: could not load library "/opt/postgresql/9.5/lib/pllua.so": libluajit-5.1.so.2: cannot open shared object file: No such file or directory
LOCATION:  internal_load_library, dfmgr.c:239`
So I ran `ldd` against `pllua.so` and got the following:
`linux-vdso.so.1 =>  (0x00007ffe7c79b000)`
`libluajit-5.1.so.2 => not found`
`libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff33f09f000)`
`/lib64/ld-linux-x86-64.so.2 (0x000055e1f1485000)`

Any ideas about why libluajit-5.1.so.2 is "not found"? I know the file exists.

Regards,

Dane

**Comment by golgote** [comment]
Same error here.

**Comment by studdugie** [comment]
A brief aside:

Following the installation instructions as written didn't work for me. Steps 1 and 2 are where the problem lay. Specifically the `export` in step 1 has no effect on the `sudo make install` in step 2 because, as I understand it, `sudo` runs `make install` in a different shell environment so the `PG_CONFIG` environmental variable created in step 1 is not visible/accessible in the new environment that `sudo` creates. What did work was: `sudo PG_CONFIG=/absolute/path/to/pg_config make install`

**Comment by golgote** [comment]
Good catch.

**Comment by golgote** [comment]
Got this error with Postgres 9.4 and luajit from Openresty:
`ERROR:  could not load library "/usr/pgsql-9.4/lib/pllua.so": /usr/pgsql-9.4/lib/pllua.so: undefined symbol: luaB_assert`

**Comment by studdugie** [comment]
Maybe OpenResty builds their luajit w/ assertions disabled? I can download and build an unmodified luajit to see if that works but I still don't know what to do about the pllua shared library not knowing where luajit is.

**Comment by golgote** [comment]
I am doing exactly that right now. About the shared library not found, no idea yet. Might be something new with 9.5, I will have to test as well. If you can try with 9.4, maybe...

**Comment by eugwne** [comment]
That is strange.. luaB_assert is private lua function, which I used inside pllua_errors (pull request #15)
I made travis build for 9.5, seems no changes needed https://travis-ci.org/eugwne/pllua/builds/100580484

**Comment by golgote** [comment]
Got the same error. No error with vanilla lua though. Looks like a path problem.

**Comment by golgote** [comment]
Maybe that's why, I am testing with your pull request from #15

**Comment by golgote** [comment]
Works fine with OpenResty LuaJit with current repository version. I guess we found a bug in your pull request then ;-)

**Comment by eugwne** [comment]
The end of this discussion in #15 and I suppose I can close it.
