### ISSUE TITLE
leak memory

### ISSUE THREAD

**Issue by jarwin123** [pllua/pllua-deprecated#39]
leak example:

create or replace test_lua_test(name text) RETURNS void AS $$
local cmd = 'select generate_series(1,150000)'
local plan = server.prepare(cmd)
local cur = plan:getcursor(nil, true)
while true do
    local r = cur:fetch(1)  
    if r == nil then break end
end
cur:close()
$$ language pllua

in this case， when i call `SPI_execute('select test_lua_test('hell0')... )`  in server programer pointend, the memory is leak.

**Comment by jarwin123** [comment]
can you help me？

**Comment by jarwin123** [comment]
have someone in here？

**Comment by eugwne** [comment]
What is the difference with #32   ?

**Comment by jarwin123** [comment]
the same as #32

**Comment by golgote** [comment]
Closing duplicate #32
