### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by df7cb** [pllua/pllua-deprecated#40]
Hi,

the Debian pllua package is still stuck at 1.0. Do you plan to make a new release soonish? A git tag on github would be enough I think so we can grab the tarball from the /archive url there.

Thanks!

**Comment by jarwin123** [comment]
pllua version is like nobody maintain ， i have submit some bug，But nobody to answer me！

**Comment by eugwne** [comment]
@mbalmer , @golgote what do you think?

**Comment by mbalmer** [comment]
> Am 26.09.2016 um 15:13 schrieb Eugene Sergeev notifications@github.com:
> 
> @mbalmer , @golgote what do you think?

I’d be fine with that.  Do you tag and release? (aka, do you do the work…;)

**Comment by eugwne** [comment]
I'm not sure that I'd like to make a release right now. It has new features, but not all bugs are fixed.

**Comment by mbalmer** [comment]
Well, you suggested a release... If you think it is too early, then we wait, of course.

**Comment by eugwne** [comment]
done
