### ISSUE TITLE
randomseed

### ISSUE THREAD

**Issue by golgote** [pllua/pllua-deprecated#7]
math.random() always returns the same results for each connection. Example code :

```
CREATE OR REPLACE FUNCTION luarand() RETURNS int LANGUAGE pllua VOLATILE AS $$
    local rand = math.random
    return rand(1, 32)
$$;
```

**Comment by eugwne** [comment]
I'm not sure what is the difference between using for math.random lua (in zero brain studio) and pllua, but math.random(1,32) in zero brain studio gives me the same result each time, from command line not the same result,  pllua luarand() gives me different numbers, but I suppose if it is the same than math.randomseed should change that.

**Comment by golgote** [comment]
I guess that there is a difference between Luajit and Lua here, because it seems that Luajit requires randomseed to be called each time, while Lua doesn't. And because os.time() is only up to the seconds, it requires to be seeded with something else, for example socket.gettime(). I need to check how Postgresql random() function works.

Here is my updated pl/lua function code to generate a random string:
https://gist.github.com/golgote/548f0b0b6fd4acf2b75e#file-random_string-lua

In my benchmarks, this function takes less than 900ms to insert 1000000 random strings (luajit, and 1300ms with Lua standard), while the plpgsql equivalent takes more than 5100ms.

**Comment by golgote** [comment]
Lua and Luajit do not generate randomseed the same way apparently. So this is not a PL/Lua issue. Closing it.
